# Generated by Django 4.1.7 on 2023-03-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('rank', models.IntegerField(null=True, verbose_name='CMC Rank')),
                ('max_supply', models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Max Supply')),
                ('supply', models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Total Supply')),
                ('symbol', models.CharField(max_length=100, unique=True, verbose_name='Symbol')),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Market Cap')),
                ('percent_change_1h', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Change in 1h')),
                ('percent_change_24h', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Change in 24h')),
                ('percent_change_7d', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Change in 7d')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('volume_24h', models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Volume in 24h')),
            ],
            options={
                'verbose_name': 'Cryptocurrency',
                'verbose_name_plural': 'Cryptocurrencies',
                'ordering': ['rank'],
            },
        ),
    ]
