# Generated by Django 4.1.7 on 2023-03-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='market_cap',
            field=models.IntegerField(null=True, verbose_name='Market Cap'),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='max_supply',
            field=models.IntegerField(null=True, verbose_name='Max Supply'),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='supply',
            field=models.IntegerField(null=True, verbose_name='Total Supply'),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='volume_24h',
            field=models.IntegerField(null=True, verbose_name='Volume in 24h'),
        ),
    ]
